#!/bin/sh

# master 브랜치에 있는지 확인
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [ "$current_branch" = "master" ]; then
    # 태그 생성 로직
    # 예: 가장 최근 태그를 기반으로 새 태그 생성
    latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
    version_number=${latest_tag#v}
    IFS='.' read -r major minor patch <<< "$version_number"
    new_patch=$((patch + 1))
    new_version="$major.$minor.$new_patch"
    git tag -a "$new_version" -m "New release $new_version"

    echo "Created new tag $new_version on master branch"

    # 새로운 태그 푸시
    git push origin "$new_version"
fi