# docker-compose.yml Databases

version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    tty: true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true

volumes:
  postgres_data:

networks:
  default:
    external:
      name: common_network
