# docker-compose.yml Databases

version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - CELERY_BROKER_URL=redis://redis:6379/2

  flower:
    build: .
    image: mher/flower
    command: celery -A config flower --address=0.0.0.0 --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production

volumes:
  postgres_data: