# Generated by Django 4.1.10 on 2024-01-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_sequence_alter_giveproduct_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='sequence',
            new_name='ordering',
        ),
    ]
