# Generated by Django 4.1.10 on 2024-04-27 08:46
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_ref_pk', models.CharField(db_index=True, max_length=100, verbose_name='Vote Reference Primary Key')),
                ('vote_ref_pk_type', models.CharField(db_index=True, max_length=100, verbose_name='Vote Type')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Vote Reason for Type')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Vote Start Date')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Vote End Date')),
                ('title', models.CharField(max_length=100, verbose_name='Vote Title')),
                ('description', models.TextField(verbose_name='Vote Description')),
                ('status', models.CharField(choices=[('READY', '아직 시작 안함'), ('VOTING', '투표 중'), ('FINISHED', '투표 종료'), ('CANCELED', '투표 취소')], max_length=100, verbose_name='Vote Status')),
                ('need_to_finish_vote_number', models.IntegerField(default=0, verbose_name='Need to Finish Vote Number')),
                ('current_finish_vote_number', models.IntegerField(default=0, verbose_name='Current Finish Vote Number')),
                ('is_multiple_selection', models.BooleanField(default=False, verbose_name='Multiple Selection')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Vote Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote Deleted Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표',
            },
        ),
        migrations.CreateModel(
            name='VoteRewardStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_ref_pk', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Reward Reference Primary Key')),
                ('reward_ref_pk_type', models.CharField(blank=True, choices=[('PROJECT', '프로젝트'), ('MEMBER_ATTRIBUTE', '성격')], max_length=100, null=True, verbose_name='Reward Reference Primary Key Type')),
                ('reward_applied_status', models.CharField(choices=[('NOT_APPLIED', '미적용'), ('APPLIED', '적용됨'), ('ROLLBACK', '취소됨')], max_length=100, verbose_name='Vote Reward Applied Status')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote Reward Applied Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.vote')),
            ],
            options={
                'verbose_name': '투표 보상 저장소',
                'verbose_name_plural': '투표 보상 저장소',
            },
        ),
        migrations.CreateModel(
            name='VotingDefaultSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Vote Default Selection Type')),
                ('display_name', models.CharField(max_length=100, verbose_name='Vote Default Selection Displaying Name')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Vote Default Selection Name')),
                ('description', models.TextField(verbose_name='Vote Default Selection Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '투표 기본 답변',
                'verbose_name_plural': '투표 기본 답변',
            },
        ),
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('additional_message', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.vote')),
            ],
            options={
                'verbose_name': '투표지',
                'verbose_name_plural': '투표지',
            },
        ),
        migrations.CreateModel(
            name='VotingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_ref_pk', models.CharField(db_index=True, max_length=100, verbose_name='Voting Answer Reference Primary Key')),
                ('answer_ref_pk_type', models.CharField(choices=[('DEFAULT_SELECTION', '기본 선택 동의 비동의'), ('MEMBER_ATTRIBUTE', '회원 속성')], max_length=100, verbose_name='Voting Answer Reference PK Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voting_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.votingrecord')),
            ],
            options={
                'verbose_name': '투표지의 투표 답변',
                'verbose_name_plural': '투표지의 투표 답변',
            },
        ),
        migrations.CreateModel(
            name='VoteRewardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_target_pk', models.CharField(db_index=True, max_length=100, verbose_name='Reward Target Primary Key')),
                ('reward_target_pk_type', models.CharField(choices=[('MEMBER', '회원')], max_length=100, verbose_name='Reward Target Primary Key Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote_reward_storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.voterewardstorage')),
            ],
            options={
                'verbose_name': '투표 보상 대상',
                'verbose_name_plural': '투표 보상 대상',
            },
        ),
    ]
