# Generated by Django 4.1.10 on 2023-12-29 09:10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_create_admin_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_nickname', models.CharField(db_index=True, max_length=45, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_joined_at', models.DateTimeField(db_index=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '비회원',
                'verbose_name_plural': '비회원',
            },
        ),
    ]
