# Generated by Django 4.1.10 on 2023-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
