# Generated by Django 4.1.10 on 2023-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_guest_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
