# Generated by Django 4.1.10 on 2023-12-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_create_admin_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
