# Generated by Django 4.1.10 on 2024-03-24 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_memberattributetype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('member_attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.memberattributetype')),
            ],
            options={
                'verbose_name': '회원 속성',
                'verbose_name_plural': '회원 속성',
            },
        ),
    ]
