# Generated by Django 4.1.10 on 2024-03-24 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_memberattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttributeAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField()),
                ('acquisition_action_pk', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('acquisition_action_pk_type', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', '습득'), ('REVOKED', '회수')], default='RECEIVED', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('member_attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.memberattributetype')),
            ],
            options={
                'verbose_name': '회원 속성 획득',
                'verbose_name_plural': '회원 속성 획득',
            },
        ),
    ]
