# Generated by Django 4.1.10 on 2023-12-31 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0008_guest_blacklist_reason_guest_is_blacklisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.BigIntegerField(db_index=True)),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.guest')),
            ],
            options={
                'verbose_name': 'Guest 포인트',
                'verbose_name_plural': 'Guest 포인트',
            },
        ),
    ]
