# Generated by Django 4.1.10 on 2024-02-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpoint',
            name='type',
            field=models.CharField(choices=[('NORMAL_POINT', '포인트')], db_index=True, default='NORMAL_POINT', max_length=255),
        ),
        migrations.AddField(
            model_name='guestpoint',
            name='valid_from',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guestpoint',
            name='valid_until',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
