# Generated by Django 4.1.10 on 2024-02-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '배너', 'verbose_name_plural': '배너'},
        ),
        migrations.AlterModelOptions(
            name='promotionrule',
            options={'verbose_name': '프로모션 기본 규칙', 'verbose_name_plural': '프로모션 기본 규칙'},
        ),
        migrations.AlterModelOptions(
            name='promotiontag',
            options={'verbose_name': '프로모션 Tag', 'verbose_name_plural': '프로모션 Tag'},
        ),
    ]
