# Generated by Django 4.1.10 on 2024-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_banner_options_alter_promotionrule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionrule',
            old_name='target_url',
            new_name='external_target_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='target_layer',
            field=models.CharField(choices=[('HOME_TOP', '홈 상단')], max_length=100, null=True, verbose_name='Banner target'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='target_pk',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Action for using pk'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='target_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Action for using type'),
        ),
    ]
