# Generated by Django 4.1.10 on 2024-04-07 03:11
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('PROJECT_UPDATE', '프로젝트 업데이트'), ('PROJECT_DELETE', '프로젝트 삭제'), ('PROJECT_RECRUIT', '프로젝트 모집')], help_text='권한', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('WAITING', '대기'), ('DELETED', '삭제')], help_text='상태', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('member', models.ForeignKey(help_text='멤버', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
            ],
        ),
    ]
