# Generated by Django 4.1.10 on 2024-04-07 03:52
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_projectmanagementpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_project_recruit', models.PositiveIntegerField(db_index=True, help_text='모집 횟수 (처음 생성 시 1, 추가 모집 시 Project recruitment_time + 1)')),
                ('recruit_status', models.CharField(choices=[('RECRUITING', '모집중'), ('RECRUIT_FINISH', '모집 완료')], default='RECRUITING', max_length=100)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('created_member', models.ForeignKey(help_text='생성자', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
            ],
        ),
    ]
