# Generated by Django 4.1.10 on 2024-04-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectrecruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='표시명', max_length=256)),
                ('name', models.CharField(db_index=True, help_text='명칭', max_length=256)),
                ('description', models.TextField(help_text='설명')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
            ],
        ),
    ]
