# Generated by Django 4.1.10 on 2024-04-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.ManyToManyField(help_text='프로젝트 기간', to='project.projectduration', verbose_name='프로젝트 기간'),
        ),
    ]
