# Generated by Django 4.1.10 on 2024-04-07 04:21
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
        ('project', '0005_project_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecruitmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_limit', models.PositiveIntegerField(db_index=True, help_text='총 제한 인원')),
                ('current_recruited', models.PositiveIntegerField(db_index=True, default=0, help_text='현재 모집 인원')),
                ('recruit_status', models.CharField(choices=[('RECRUITING', '모집중'), ('RECRUIT_FINISH', '모집 완료')], default='RECRUITING', help_text='모집 상태', max_length=100)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('created_member', models.ForeignKey(help_text='생성자', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='직무', on_delete=django.db.models.deletion.DO_NOTHING, to='job.job')),
                ('project_recruitment', models.ForeignKey(help_text='프로젝트 모집', on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectrecruitment')),
            ],
        ),
    ]
