# Generated by Django 4.1.10 on 2024-04-07 04:41
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_projectrecruitmentjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecruitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(help_text='신청 메시지')),
                ('request_status', models.CharField(choices=[('IN_REVIEW', '검토중'), ('ACCEPTED', '승인'), ('REJECTED', '거절'), ('CANCELED', '취소')], default='IN_REVIEW', help_text='신청 상태', max_length=100)),
                ('request_status_updated_at', models.DateTimeField(blank=True, help_text='신청 상태 수정 일시', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('member', models.ForeignKey(help_text='신청 멤버', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project_recruitment_job', models.ForeignKey(help_text='프로젝트 모집 직무', on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectrecruitmentjob')),
            ],
        ),
    ]
