# Generated by Django 4.1.10 on 2024-04-07 05:03
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('project', '0007_projectrecruitapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemberManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_status', models.CharField(blank=True, choices=[('BANNED', '강퇴'), ('LEFT', '탈주')], help_text='프로젝트 탈퇴 상태', max_length=100, null=True)),
                ('is_leader', models.BooleanField(default=False, help_text='리더 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('left_status_updated_at', models.DateTimeField(blank=True, help_text='프로젝트 탈퇴 상태 수정 일시', null=True)),
                ('job', models.ForeignKey(help_text='프로젝트에서 맡고 있는 직무', on_delete=django.db.models.deletion.DO_NOTHING, to='job.job')),
                ('project_recruit_application', models.ForeignKey(help_text='프로젝트지원서', on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectrecruitapplication')),
            ],
        ),
    ]
