# Generated by Django 4.1.10 on 2024-04-07 05:15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0015_memberattributeacquisition'),
        ('project', '0008_projectmembermanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemberAttributeReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('given_member', models.ForeignKey(help_text='발송인', on_delete=django.db.models.deletion.DO_NOTHING, related_name='given_members', to=settings.AUTH_USER_MODEL)),
                ('member_attribute_type', models.ForeignKey(help_text='멤버 속성 타입', on_delete=django.db.models.deletion.DO_NOTHING, to='member.memberattributetype')),
                ('project', models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
                ('received_member', models.ForeignKey(help_text='수취인', on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
