# Generated by Django 4.1.10 on 2024-04-07 05:20
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_projectmemberattributereferralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bookmark_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='북마크 수', verbose_name='북마크 수'),
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제 일시', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('member', models.ForeignKey(help_text='멤버', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
            ],
        ),
    ]
