# Generated by Django 4.1.10 on 2024-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_bookmark_count_projectbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rearrangement_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='정렬 기준 시간', verbose_name='정렬 기준 시간'),
        ),
    ]
