# Generated by Django 4.1.10 on 2024-05-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_rearrangement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='종료 시간', null=True, verbose_name='종료 시간'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='시작 시간', null=True, verbose_name='시작 시간'),
        ),
    ]
