# Generated by Django 4.1.10 on 2024-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_project_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.ManyToManyField(blank=True, help_text='프로젝트 기간', null=True, to='project.projectduration', verbose_name='프로젝트 기간'),
        ),
    ]
