# Generated by Django 4.1.10 on 2024-05-26 06:25
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('project', '0015_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_project_recruitment',
            field=models.ForeignKey(blank=True, help_text='최신 프로젝트 모집', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_project_recruitment', to='project.projectrecruitment', verbose_name='최신 프로젝트 모집'),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_project_recruitment_jobs',
            field=models.ManyToManyField(help_text='최신 프로젝트 모집 직무들', related_name='latest_project_recruitment_jobs', to='job.job'),
        ),
    ]
