# Generated by Django 4.1.10 on 2024-06-22 08:31
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('project', '0017_alter_projectmembermanagement_project_recruit_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembermanagement',
            name='job',
            field=models.ForeignKey(blank=True, help_text='프로젝트에서 맡고 있는 직무', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.job'),
        ),
    ]
