# Generated by Django 4.1.10 on 2024-06-22 08:49
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_projectmembermanagement_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembermanagement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='프로젝트', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.project'),
        ),
    ]
