# Generated by Django 4.1.10 on 2024-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projectmembermanagement_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecruitmentjob',
            name='total_limit',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='총 제한 인원', null=True),
        ),
    ]
