# Generated by Django 4.1.10 on 2024-07-06 12:29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0020_alter_projectrecruitmentjob_total_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembermanagement',
            name='member',
            field=models.ForeignKey(blank=True, help_text='멤버', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
