# Generated by Django 4.1.10 on 2024-07-27 12:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_projectmembermanagement_member'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
