# Generated by Django 4.1.10 on 2024-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_title_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='icon_image',
            field=models.TextField(blank=True, help_text='이미지', null=True, verbose_name='이미지'),
        ),
    ]
