# Generated by Django 4.1.10 on 2024-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_once_refunded',
            field=models.BooleanField(default=False, verbose_name='한번이라도 환불 했는지 여부'),
        ),
    ]
