name: Docker Image Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64

    - name: Docker Hub Login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Docker Image Build
      run: |
        docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:latest . --push
