name: Docker Image Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Docker Hub Login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Docker Set my builder
      run: |
        docker buildx create --name mybuilder --use

    - name: Docker Image Build
      run: |
        docker buildx build --platform linux/arm64/v8 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:latest .

    - name: Docker Image Push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:latest
