name: Test

on:
  pull_request:
    # needs to create code-review branch
    branches: [ code-review ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      postgres:
        image: postgres14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: siple_test
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        DJANGO_SETTINGS_MODULE: config.settings.local
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Wait for Postgres
      run: |
        until pg_isready -h 127.0.0.1 -p 5432; do
        echo "Waiting for postgres to be ready..."
        sleep 1
        done
    - name: Set up Database
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: siple_test
      run: |
        psql -h 127.0.0.1 -U postgres -d siple_test -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Database Settings
      run: |
        python manage.py migrate --noinput
    - name: Run Tests
      run: |
        python manage.py test --noinput
