name: Test

on:
  pull_request:
    # needs to create code-review branch
    branches: [ code-review ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        DJANGO_SETTINGS_MODULE: config.settings.local
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Database Settings
      run: |
        python manage.py migrate --noinput
    - name: Run Tests
      run: |
        python manage.py test --noinput
